apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: car-dealership
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard  ← SUPPRIMEZ cette ligne



# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: redis-pvc
#   namespace: car-dealership
#   labels:
#     app: redis
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: standard