# services:
#   mysql:
#     image: mysql:8.0
#     container_name: car_dealership_mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       MYSQL_DATABASE: car_dealership
#       MYSQL_USER: car_user
#       MYSQL_PASSWORD: car_password
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/01-setup.sql
#       - ./scripts/sample_data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql
#     ports:
#       - "3310:3306"  # Expose le port 3306 du container sur 3307 localement
#     networks:
#       - car_dealership_network
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10

#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: car_dealership_api
#     restart: unless-stopped
#     depends_on:
#       mysql:
#         condition: service_healthy
#     environment:
#       DATABASE_URL: mysql+pymysql://car_user:car_password@mysql:3306/car_dealership
#       SECRET_KEY: quantum-motors-secret-key-change-in-production-with-long-random-string
#       ALGORITHM: HS256
#       ACCESS_TOKEN_EXPIRE_MINUTES: 30
#       APP_NAME: Car Dealership API
#       APP_VERSION: 1.0.0
#       DEBUG: "true"
#       CORS_ORIGINS: '["http://localhost:3000","http://localhost:8080","http://localhost:5173","http://localhost:8501"]'
#       DEFAULT_PAGE_SIZE: 20
#       MAX_PAGE_SIZE: 100
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./app:/app/app
#       - ./scripts:/app/scripts
#       - api_logs:/app/logs
#       - api_uploads:/app/uploads
#     networks:
#       - car_dealership_network
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 40s

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     container_name: car_dealership_phpmyadmin
#     restart: unless-stopped
#     depends_on:
#       mysql:
#         condition: service_healthy
#     environment:
#       PMA_HOST: mysql
#       PMA_PORT: 3306
#       PMA_USER: car_user
#       PMA_PASSWORD: car_password
#       MYSQL_ROOT_PASSWORD: root_password
#     ports:
#       - "8081:80"
#     networks:
#       - car_dealership_network

#   redis:
#     image: redis:7-alpine
#     container_name: car_dealership_redis
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     networks:
#       - car_dealership_network
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

# networks:
#   car_dealership_network:
#     driver: bridge
#     name: car_dealership_network

# volumes:
#   mysql_data:
#     name: car_dealership_mysql_data
#   redis_data:
#     name: car_dealership_redis_data
#   api_logs:
#     name: car_dealership_api_logs
#   api_uploads:
#     name: car_dealership_api_uploads

