apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: car-dealership
  labels:
    app: frontend
    component: ui
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30851
    protocol: TCP
    name: http
  selector:
    app: frontend